### ISSUE TITLE
audio description support

### ISSUE THREAD

**Issue by goetsu** [ghinda/acornmediaplayer#1]
Hi,

is there any plan to support audio description ? maybe it can be achieve by using an extra synchronized audio element.

Regards,

Aurélien

**Comment by ghinda** [comment]
Hey Aurélien,
Are you referring to a simple description to an audio element, or synchronized captions?

If you're talking about synced captions, these could be implemented similar to captions used for video elements.

The only problem is that I'm pretty busy right now, and don't really have enough time to develop new features very soon. 
If you, or somebody else, would like to implement any features, I'd be glad to include them in the project.

**Comment by elz64** [comment]
Hi,

I trying to setup an AD too.
AD is a second player reading an mp3 sound file only (<audio>) which is fired  synchronously with the video one.

So 1st quastion: how to setup 2 instance of acorn  (I m sorry if obvious)

**Comment by ghinda** [comment]
Hi @elz64,
Acorn supports multiple instances of the player on the same page, as you can see on the [demos page](http://ghinda.net/acornmediaplayer/demos.html).

Having two audio/video elements in sync is a different story, and not a feature of the player. But, since the player attaches listeners directly to the media events, you should be able to use something standard like this example on html5demos.com http://html5demos.com/two-videos.
