### ISSUE TITLE
Not workin in -WebKit- in Win 7/8

### ISSUE THREAD

**Issue by Tusko** [ghinda/acornmediaplayer#9]
Hi, Your videoplayer not work in WebKit browsers 
(Safari windows, Google Chrome (v. 25.0.1364.172 m), Maxthon Cloud Browser v3)

In sources I'm add the .OGG video type

< source src="/path/video.mp4" type="video/mp4" >
< source src="/path/video.webm" type="video/webm" >
< source src="/path/video.ogv" type="video/ogg" >

in .htaccess

AddType video/ogg .ogv
AddType video/ogg .ogg
AddType video/mp4 .mp4
AddType video/webm .webm

It's not help, also.

Seeking a solution urgently!!!
Need You help.

http://belugalabsdev.com/colony/

Thank You

**Comment by ghinda** [comment]
Hi @Tusko,

I can't seem to be able to replicate the issue. The video seems to work fine on http://ghinda.net/acornmediaplayer/.

A while ago, I've noticed an issue with the order of the video (formats), in Chrome at least. I had to specify the `.webm` source first, in order for Chrome to play it. Specifying the `.mp4` source first caused the video not to play at all.

This is how it looks on the demo page:
`<source type="video/webm" src="https://acornmedia.herokuapp.com/media/tears_of_steel_480.webm" />`
`<source type="video/mp4" src="https://acornmedia.herokuapp.com/media/tears_of_steel_480.mp4" />`.

You really shouldn't have to use `.ogv` anymore, since all browsers that support `ogv` also support `webm` now. Also, Android supports `webm` but does not support `ogv`, and has flaky support for `mp4`, so using `webm` and `mp4` should be enough.

**Comment by Tusko** [comment]
@ghinda 
At Your demo page player does not work in my chrome

http://ghinda.net/acornmediaplayer/

**Comment by ghinda** [comment]
That's weird. I've tested in Chrome 26 on both Windows and Ubuntu, and it seems to work fine. Are you sure it's not buffering?

**Comment by Tusko** [comment]
in Chrome v26 it works fine. But how I can to report user for update his browser?

in Maxthon works after 2-3 minutes of dowloading video.

Safari (windows) - not works :(

**Comment by ghinda** [comment]
That's weird. I'll have to look into it, but probably only next week sometime.

**Comment by Tusko** [comment]
Thank You, I'll be waiting :)

**Comment by ghinda** [comment]
I'm going to close this, since I can't replicate the issue. I have tested on Safari (OSX since the Windows version is no longer supported) and Chrome.

**Comment by Tusko** [comment]
It is not important. I wrote a custom player
